(setq ireallylikelisp t)
(setq idontlikelisp (not t))
(if (not (or (not ireallylikelisp) idontlikelisp)) 
  (write (not (or (not ireallylikelisp) idontlikelisp)))
  (write (not (not (or (not ireallylikelisp) idontlikelisp))))
) 
